### PR TITLE
Adds `input_gamepad_check_any`

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by offalynne** [comment]
Review #398 first to avoid merge conflict

**Comment by JujuAdams** [comment]
If we add `gp_any` could we avoid creating new functions? Would like to squeeze this into 5.0 if possible but adding new functions would make this a 5.1 feature.

**Comment by offalynne** [comment]
Can do

**Comment by offalynne** [comment]
Question is what to do about the second parameter here, otherwise doable, yeah

**Comment by JujuAdams** [comment]
Separate into `gp_any_button` and `gp_any_axis`?

**Comment by offalynne** [comment]
Hmmm OK

**Comment by offalynne** [comment]
Not sure I like that either, actually. Where the extended SDL buttons are explicit and harmless if used incorrectly, any/none can’t be handled in a way that’s friendly (eg not crashing) if used incorrectly with inbuilt functions, and adding them puts them right there in autocomplete.

Would also bloat the direct checkers a bit. I’m fine with calling this 5.1 but can reauthor with none/any if you still prefer.

**Comment by JujuAdams** [comment]
Why would they cause crashes? Wouldn't those constants be 32795 + 32796?

**Comment by offalynne** [comment]
@JujuAdams they could be ! and less of an issue that way.

i suppose they could be set in gamepad tick as well then, to avoid bloating the checkers.

lmk if the below scheme looks OK:
```
gp_any
gp_none
gp_button_any
gp_button_none
gp_axis_any
gp_axis_none
```

**Comment by JujuAdams** [comment]
Looks good to me 👍

**Comment by offalynne** [comment]
@JujuAdams I'm having trouble deciding how to scope the values to check.
For the fields `any_button, any_axis` on gamepad class: 
Should the gamepad object's tick method set these ?  `with mappings { tick(); other.[..] = [..]; }`
Or the gamepad mapping object's tick method ? `with global.gamepads[_gamepad] { [..] = _[..] }`

**Pull request closed without merging**
