### PR TITLE
Clean up Steamworks device handling

### PR DESCRIPTION
**Pull request by offalynne**
Previously a change in Steam Input handles did full rediscovery on all gamepads which was problematic, now we only reevaluate the relevant changes

### CODE REVIEW

**Comment by JujuAdams** [comment]
For failure cases, e.g. we don't recognise a Steam description, this code with nope out with a judicious `return` call. However, `__steam_handle` has been set. Is this problematic?

**Comment by offalynne** [comment]
This is how it was before, but can probably do a little better. Will fix

**Comment by offalynne** [comment]
On review I'm content with this. Early out in absence of recognized Steam type falls back to initialised values which is correct, there is no need to revalidate or force a fallback type.

**Comment by JujuAdams** [comment]
Great! Merging...

**Pull request merged**
