### PR TITLE
Switch controller identification

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by JujuAdams** [comment]
For the purposes of compliance checking, handheld mode + joycon pair have to be separate types (if one was to draw a picture of what the user is holding - e.g. controller assignment - it has to show the literal device). Could you make that change please?

**Comment by offalynne** [comment]
doon

**Comment by JujuAdams** [comment]
Thank you very much!

Are there any changes that need to happen in documentation for this?

**Comment by offalynne** [comment]
Just the types table, will update.

Edit: Done.

**Comment by JujuAdams** [comment]
Final (copy)(copy).psd

**Comment by JujuAdams** [comment]
Gonna accept this under the proviso that a buttload of issues exist with Input's implementation on Switch (that I'll fix today, hopefully)

**Pull request merged**
