### PR TITLE
Extends keycode constants and handles UTF-8

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by JujuAdams** [comment]
Big fan of these new constants. How do we feel about `vk_backtick` rather than `vk_grave`? The former is probably more commonly understood by developers these days but the latter is arguably more correct.

**Comment by offalynne** [comment]
Yeah I flip flopped a bit, perhaps a Discord poll is in order https://en.wikipedia.org/wiki/Backtick

**Comment by JujuAdams** [comment]
Agreed! Shall run it now

**Comment by offalynne** [comment]
rip grave we barely knew ye

**Comment by JujuAdams** [comment]
Am I going to be able to convince you that `vk_grave` isn't needed at all and we should keep it simple?

**Comment by offalynne** [comment]
Alack, it is already deceased: https://github.com/JujuAdams/Input/pull/244/commits/e2915fab12ee4faeccdfaddffd1da5a0e02a4f98#

**Comment by JujuAdams** [comment]
Pour one out for our friend and ally the grave accent

**Pull request merged**
