### PR TITLE
Adds button label and color data

### PR DESCRIPTION
**Pull request by offalynne**
Preliminary, data only

- PlayStation [[1](https://web.archive.org/web/20160307150124/http://www.1up.com/news/playstation-1-design#:~:text=we%20went%20with-,icons%20or%20symbols,-%2C%20and%20I%20came)] 
- Xbox [[1](https://venturebeat.com/2013/11/20/the-xbox-one-controller-whats-new-with-the-buttons-and-triggers-part-3-exclusive/#:~:text=Xbox%20One%20controller.-,The%20face%20buttons,The%20spacing,-Microsoft%20tightened%20up)]
- Nintendo [[1](https://www.nintendo.com/super-nes-classic/interview-star-fox-2/#:~:text=design%20around%20the-,a%2C%20b%2C%20x%20and%20y%20buttons,-%2C%20as%20well%20as)] [[2](https://www.raphnet.net/design/console_colors/index_en.php#:~:text=HTML%3A%20%23C1121C-,Super%20Famicom,them%20as%20close%20matches.,-Super%20Nintendo)] [[3](https://i.ytimg.com/vi/PxgDwkuPhhg/maxresdefault.jpg)]
- Apple [[1](https://developer.apple.com/library/archive/documentation/ServicesDiscovery/Conceptual/GameControllerPG/Introduction/Introduction.html)]
- Stadia [[1](https://support.google.com/stadia/answer/9565956?hl=en-CA&ref_topic=9495415)]
- Luna [[1](https://www.amazon.com/gp/help/customer/display.html?nodeId=GEKGVPKSY8B2RGHG)]
- Dreamcast [[1](https://www.digitpress.com/library/manuals/dreamcast/controller.pdf)] [[2](http://bp1.blogger.com/_dTJCOGBUipA/SJDdPYK-R_I/AAAAAAAAAjI/F6KgCorokZk/s1600-h/manual2.jpg)]
- Ouya [[1](https://apprize.best/gadget/ouya/ouya.files/image037.jpg)]
- Steam [[1](https://partner.steamgames.com/doc/features/steam_controller/device/steam_controller)]

### CODE REVIEW

**Comment by offalynne** [comment]
Not prescribing specific color values as specs vary and library user should select appropriate color contrast based on context.

Colors are fun but labels are recommended only for use in testing -- glyphs should be used instead of names (gamepad constant per type -> sprite) as icons match better than descriptions and are friendlier to localization.

**Comment by offalynne** [comment]
Waffled on the value of raw typing Dreamcast, justified since

- Aliases to Xbox 360 simple type
- Multiple adapters (Mayflash, Raphnet, Blissbox)
- Multiple new models (Retrofighters, Retrobit forthcoming)

**Comment by JujuAdams** [comment]
Dunno how out there this is, but would it be possible to find #RRGGBB values for button colours?

**Comment by JujuAdams** [comment]
Also typo for `CommunityGameCube` - `righthtshoulder`

**Comment by offalynne** [comment]
> RRGGBB 

I had them in there initially but backed them out as

> specs vary and library user should select appropriate color contrast based on context

Xbox and Apple colors are supersaturated whereas the PlayStation ones are bright, and Nintendo (on consoles with colored buttons) don't specify. Personally I'd rather we not prescribe fixed values, but I can pull them from official sources if it's preferable.

What format would you want ? BGR integer ?

**Comment by JujuAdams** [comment]
An excellent point. Let's stick to colour names for now.

**Comment by JujuAdams** [comment]
Thank you for putting together the source data, I'll implement a getter now

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/b7f6cffc8943c2a016de36b1620ced221be8461f

**Comment by offalynne** [comment]
thank you ! will test and write some docs

**Comment by JujuAdams** [comment]
Cheer m'dears

**Pull request merged**
