### PR TITLE
Better gyro support for mixed and multidevice modes, fixes Steam Input crash

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by offalynne** [comment]
Think I’m gonna slice out the value summing forand instead add some “last gamepad used” logic to MIXED source mode.

**Comment by JujuAdams** [comment]
Why does `input_motion_data_get()` need a gamepad argument when `input_gyro_params_set()` allows the developer to set which gamepad is preferred?

**Comment by offalynne** [comment]
Mm yeah that's unnecessary, thanks will edit

**Comment by JujuAdams** [comment]
Looks good! Thank you

**Pull request merged**
