### PR TITLE
Adds Included Files subdirectory option to config

### PR DESCRIPTION
**Pull request by stoozey**
Whenever I use Input I always end up changing it to support this, would be great to have this built-in.

### CODE REVIEW

**Comment by JujuAdams** [comment]
@offalynne thoughts?

**Comment by offalynne** [comment]
definitely like the idea of being able to compartmentalize datafiles especially for managing multiple libraries & extensions

important to note the path (should the library user set one) should use forward slash between directories for cross platform compatibility

i'd prefer if the final path was built where the macros are used rather than in the system macros themselves -- if you're going to merge this as authored, then the `__input_system` macros should be renamed from `_FILENAME` to `_FILEPATH`

**Comment by JujuAdams** [comment]
Thought about this for a bit, and I'm going to decline to merge this PR.

1. Subdirectories inside Included Files have serious, perennial problems cross-platform. Scribble has numerous [edge case checks](https://github.com/JujuAdams/Scribble/blob/master/scripts/__scribble_init/__scribble_init.gml#L8-L29) where subdirectories act strangely or outright do not work. This includes iOS, Android, and HTML5. I've also had bugs reports recently that subdirectories have issues on console platforms as well. In truth, I'm looking at ways to _remove_ the Included Files subdirectory from Scribble because of all the problems with them.

2. Scribble has a subdirectory macro because the most common use case is for Scribble to automatically index font .yy files, and those files sometimes want to be placed inside a subdirectory. That subdirectory needs to be specified somewhere. For Input, I agree that the use case for a subdirectory macro is there, but adding an extra step of a subdirectory macro is unnecessary when the subdirectory can be baked into each file path macro.

3. If developers are loading Scribble files manually by name then it's tedious to specify exact paths for every path. In Input, there're only three paths. It's not a lot of work (provided those filenames are publicly configurable).

What I will do, however, is move the filename macros into the public config file. That way you can slot in the subdirectory yourself without Input having to officially support this feature.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/2ab8f585f6f4c77f63024e9009092b23f59b54fe

**Pull request closed without merging**
