### PR TITLE
Adds SDL2 extended buttons

### PR DESCRIPTION
**Pull request by offalynne**
Adds `gp_touchpad`, `gp_paddle1`, `gp_paddle2`, `gp_paddle3`, `gp_paddle4` and supplements relevant cases.

### CODE REVIEW

**Comment by offalynne** [comment]
Make sure to set `INPUT_SDL2_ALLOW_EXTENDED` to `false` before merge

**Comment by JujuAdams** [comment]
Is the mapping of touchpads on PS4/PS5 gamepads only limited to Windows and MacOS? Doesn't work on Linux? Do touchpads work via browsers on Windows/MacOS? Do browsers on Linux support touchpad input?

**Comment by offalynne** [comment]
> _Doesn't work on Linux_

Linux and Android ship drivers that treat the controller touchpad like any other trackpad. It's a mouse!
&nbsp;

> _Do touchpads work via browsers on Windows/MacOS?_ 

Yes ! https://github.com/JujuAdams/Input/pull/243/commits/1465905722b4cc5777113fa7c0127a66b316127f
&nbsp;


> _Do browsers on Linux support touchpad input?_

See above

**Comment by JujuAdams** [comment]
I'm confused by https://github.com/JujuAdams/Input/pull/243/files#diff-9569de4f189d2d787937948b123ecb9d71e4425ae19e2d4a7fe3ad7cabdc903bR559-R560 in that case. Why the checks against Windows + MacOS?

**Comment by offalynne** [comment]
SDL2 added extended fields long after adoption of the spec so the DB is full of PS4 controllers missing the `touchpad` field. What that bit does is confirm a normative PlayStation mapping (so Hori controllers, weirdo XInput capable PS4 controllers, etc. are skipped), in which case the correct `touchpad` value is set automatically. SDL does similar.

We do this on Windows & Mac only, as per above, Linux and Android are doing their own thing via kernel driver.

**Comment by JujuAdams** [comment]
I see. Thank you for updating the comment there

**Pull request merged**
