### PR TITLE
Refactor keyboard/mouse allowance and blocking

### PR DESCRIPTION
**Pull request by offalynne**
Mouse *blocking* (ignoring mouse input from window blur) was conflated with mouse *allowance* (per platform configuration) in an unhelpful way, fixed here.

### CODE REVIEW

**Comment by JujuAdams** [comment]
Do you think `global.__input_mouse_valid` (and keyboard/gamepad equivalents) are due for a rename?

**Comment by offalynne** [comment]
perhaps 'enabled' is closer to correct

**Comment by JujuAdams** [comment]
mmok created an issue for that: https://github.com/JujuAdams/Input/issues/214

**Comment by JujuAdams** [comment]
Thank you kindly

**Pull request merged**
