### PR TITLE
Prevent Steam aliasing PlayStation and Switch controllers to Xbox

### PR DESCRIPTION
**Pull request by offalynne**
Uses environment variables set by Steam to improve simple type lookup for virtual gamepads based on the configuration of Steam Input.

When Steam Input has opted-in PlayStation controllers, or has opted-in Switch controllers *without* configuring to swap Switch face button layout to match the XInput layout, identified Steam virtual gamepads will no longer incorrectly resolve to simple type `"xbox 360"`.

### CODE REVIEW

**Comment by JujuAdams** [comment]
Unfortunately `is_string(_steam_environ)` and `is_string(_steam_configs)` will cause issues due to bugs in `environment_get_variable()` on certain platforms. GM returns strings in error that aren't quuuuuite real strings which causes problems.

I suggest the following to filter out issues:
```
if ((_steam_environ != "") && (_steam_configs != "")) //Filter out erroneous results from environment_get_variable()
{
    if (is_string(_steam_environ) && (_steam_environ == "1")
    &&  is_string(_steam_configs) && (_steam_configs != "" )
    {
        ...
    }
}
```

**Comment by offalynne** [comment]
@JujuAdams patterned after https://github.com/JujuAdams/Input/blob/1fbfbbedd97817e1a7a374c2d2672aaec0875ea5/scripts/__input_initialize/__input_initialize.gml#L146-L147

should this be changed as well ?

**Comment by JujuAdams** [comment]
Ooooh yeah that check should be the other way round (`(_external_string != "") && is_string(_external_string)`). It's the check against the empty string that's the important bit; no matter what value you're expecting, the check agains the empty string must be in there.

**Comment by offalynne** [comment]
Thanks. Does track with other weirdness I've seen regarding testing against empty string.

**Comment by offalynne** [comment]
done twiddling, tested & good for review

**Comment by JujuAdams** [comment]
Thaaaaaaank you

**Pull request merged**
