### PR TITLE
Fixed issues with previous commits.

### PR DESCRIPTION
**Pull request by JulianDicken**

### CODE REVIEW

**Comment by tabularelf** [comment]
genie-free

**Comment by JujuAdams** [comment]
Could you link the previous commits? I'm confused which ones you're talking about.

**Comment by JulianDicken** [comment]
Specifically https://github.com/JujuAdams/Input/pull/369/commits/6b0697e7db1300e4f36b8408dc74f646cd3761ab
and https://github.com/JujuAdams/Input/pull/369/commits/4f0c7bcddf7ef8d50337f80f4e13b2a676752437
Are flawed as @JujuAdams pointed out in https://github.com/JujuAdams/Input/pull/367#issuecomment-1154398989 and https://github.com/JujuAdams/Input/pull/368#issuecomment-1154413178

**Comment by JulianDicken** [comment]
I am being sabotaged by made up conflicrs

**Comment by offalynne** [comment]
:gun:

**Pull request closed without merging**
