### PR TITLE
Don't automatically recapture mouse in borderless window mode

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by JujuAdams** [comment]
Which versions is `window_get_showborder()` available in?

**Comment by offalynne** [comment]
function is stubbed but it produces an error anyway on LTS :-\

**Comment by JujuAdams** [comment]
v_v

**Comment by JujuAdams** [comment]
We could roll this in using a try...catch?

**Comment by offalynne** [comment]
ehhh inclined to wait until someone reports as a problem ? 🤷‍♀️ my thinking is you need to self implement drag-relocation in borderless window mode if you want it (i think many games omit this ?) and if doing so, window position will update in realtime making current auto-recapture behaviour undesirable. edge on an edge.

**Comment by offalynne** [comment]
lmk if you want it and i'll add the try/catch

**Comment by JujuAdams** [comment]
Yeah let's wait until it comes up. Easy enough to implement later.

**Pull request closed without merging**
