### PR TITLE
Assign all gamepads in mixed and multisource mode

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by JujuAdams** [comment]
How do we feel about merging this into a bug fix for 5.5?

**Comment by offalynne** [comment]
ok, do i need to resubmit patch ?

**Comment by JujuAdams** [comment]
Nah I think I can change the target ...

**Comment by JujuAdams** [comment]
... yeah no that's not going to work! Please resubmit the patch.

**Comment by offalynne** [comment]
Will do but you should accept this one too probs since dev5.5 isn't forward compatible (right?)

**Comment by JujuAdams** [comment]
oh yeah lol

**Pull request merged**
