### PR TITLE
Revise touch macros

### LINKED ISSUE #676: Kill ambiguous `INPUT_TOUCH_POINTER_ALLOWED`
add `INPUT_PLAYSTATION_TOUCHPAD_IS_MOUSE` and `INPUT_SWITCH_TOUCHSCREEN_ALLOWED`

### PR DESCRIPTION
**Pull request by offalynne**
closes #676

### CODE REVIEW

**Comment by JujuAdams** [comment]
`INPUT_TOUCH_IS_MOUSE` macro name might be confusing, though I don't have a better name to suggest

**Comment by JujuAdams** [comment]
Maybe.............. `INPUT_TOUCH_DEVICE_USES_MOUSE_SOURCE`?

**Comment by JujuAdams** [comment]
I think the central issue here is that "touch" can refer to a touchscreen, a PS touchpad, and the "touch" source.

**Comment by offalynne** [comment]
yeah this is what killing `INPUT_TOUCH_POINTER_ALLOWED` was meant to clarify.. how's `INPUT_TOUCHSCREEN_USES_MOUSE_SOURCE`

**Comment by JujuAdams** [comment]
mmyepyep that's what I had originally, but would this macro also affect PlayStation touchpads? Am I worrying too much?

**Comment by offalynne** [comment]
> mmyepyep that's what I had originally, but would this macro also affect PlayStation touchpads? Am I worrying too much?

No, I sliced off PS touchpads now, they're mouse-only

**Comment by JujuAdams** [comment]
Great! `INPUT_TOUCHSCREEN_USES_MOUSE_SOURCE` it is

**Pull request merged**
