### PR TITLE
added feather comments to input checker functions

### PR DESCRIPTION
**Pull request by DragoniteSpam**
same as i did for scribble: https://github.com/JujuAdams/Scribble/pull/500 because i grow tired of feather complaining that the verb being checked isn't the keyword `all`

### CODE REVIEW

**Comment by JujuAdams** [comment]
Input uses `// feather disable all` throughout. If that's not effective then that's a GameMaker IDE bug.

**Comment by DragoniteSpam** [comment]
Feather disable all suppresses errors within the script, calls to the functions from elsewhere are still type-checked

**Comment by offalynne** [comment]
did not mean to hit reopen on this whoops lol

**Comment by offalynne** [comment]
(did not mean to reopen there whoops lol)

**Pull request closed without merging**
