### PR TITLE
Allow controller object recovery on restart, add controller object depth definition

### PR DESCRIPTION
**Pull request by offalynne**
pre patch
😦 `game_restart()`
😦 `with (all) depth = -y;`

post patch
😃

### CODE REVIEW

**Comment by JujuAdams** [comment]
What's the change in `obj_example_drop_in_gameplay` doing? Can't remember what Other 3 is

**Comment by offalynne** [comment]
dropping sources (and thus players) on Game End (restart) which was the test case i used

**Comment by JujuAdams** [comment]
Is this something we should be doing on `game_restart()` in general i.e. Is it helpful in the general case if we put the same/similar code in `input_controller_object`?

**Comment by offalynne** [comment]
perhaps best not to prescribe, `obj_example_drop_in_gameplay` merits it for the`INPUT_SOURCE_MODE.FIXED` multiplayer management stuff in it's Step event, idk if we should always dump sources/players on restart since hotswap should continue to work fine across a restart as-is. if the common restart use case is "kick back to start menu" you probably want source/player state to persist -- only issue is for games that spawn objects upon player connection, which doesn't really strike me as a first-room thing anyway

doable if desirable tho

edit: moved that stuff to Create event for clarity

**Comment by offalynne** [comment]
maybe it's good to start in a clean state for `INPUT_SOURCE_MODE.FIXED`ers ? hm.

**Comment by JujuAdams** [comment]
I suspect this line of questioning is futile because the divergence in use cases amongst users of `game_restart()` is going to be extreme

**Pull request merged**
