### PR TITLE
Rethinks optional gamepad types, removes macro

### PR DESCRIPTION
**Pull request by offalynne**

### CODE REVIEW

**Comment by JujuAdams** [comment]
I see what you mean now. We should split off this data into a separate script for ease of access. Debatable whether this needs to be an actual "config script", we can bury the script inside the `(System)` folder, but there does need to be a single point of contact for devs to find and tweak values.

**Comment by offalynne** [comment]
Hm, OK

**Comment by JujuAdams** [comment]
I'm sensing you're unconvinced?

**Comment by offalynne** [comment]
Seems fine ?

Shall force push to this branch later

**Comment by JujuAdams** [comment]
We have a winner!

**Pull request merged**
